name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.run_id }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image with run ID tag
      run: |
        docker build . --file Dockerfile --tag my-image-name:${{ env.IMAGE_TAG }}

    - name: Start sshx session (manual trigger only)
      if: github.event_name == 'workflow_dispatch'
      run: |
        curl -sSf https://sshx.io/get | sh -s run
